# Generated by Django 5.2.7 on 2025-11-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('fee', models.IntegerField()),
                ('contact', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=10)),
            ],
        ),
    ]
